---
- hosts: all
  sudo: true

  vars_files:
    - ../settings.yml

  tasks:

  - name: install misc packages
    apt: name={{ item }} state=latest
    with_items:
      - ssh
      - libglib2.0-0
      - libgtk2.0-0

  - copy: src=broadsign-player/bsplayer.deb dest=/tmp/bsplayer.deb
    notify: install bsplayer

  - name: install bsplayer
    command: dpkg -i "/tmp/bsplayer.deb"

  - name: dedicate player
    script: /opt/broadsign/suite/bsp/bin/dedicated_bsp.sh
    when: dedicated

  - name: download ngrok
    get_url: url=https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip dest=/tmp/ngrok.zip mode=0600

  - name: unzip ngrok
    command: unzip -o "/tmp/ngrok.zip" -d "/opt/ngrok/"

  - name: authorize ngrok
    command: /opt/ngrok/ngrok authtoken {{ authtoken}}

  - name: ensure ngrok will run on start-up
    template: src=templates/rc.j2 dest=/etc/rc.local
